---

- name: Ansible SSH Port
  ansible.builtin.debug:
    msg: "{{ ssh_port }}"

- name: Update repository cache
  ansible.builtin.apt:
    update_cache: true


- name: Install latest Verion of ufw # noqa package-latest
  ansible.builtin.apt:
    name: ufw
    state: latest

- name: Disable ufw and reset to defaults
  community.general.ufw:
    state: "{{ item }}"
  loop:
    - disabled
    - reset

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    direction: in

- name: Configure ufw
  ansible.builtin.import_role:
    name: weareinteractive.ufw
