---
# defaults file for oberfeldwedler.ufw-wrapper

# for more info see: weareinteractive.ufw

ssh_port: "22"

#automatically set ssh_port from ansible vars
## ssh_port: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_PORT') }}"

# List of rules to be applied
# see https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html for documentation
## ufw_rules:
##   - rule: allow
##     to_port: 22


ufw_rules:
- logging: "low"

# Manage the configuration file
ufw_manage_config: false

# Configuration object passed to the configuration file
ufw_config:
  IPV6: "yes"
  DEFAULT_INPUT_POLICY: DROP
  DEFAULT_OUTPUT_POLICY: ACCEPT
  DEFAULT_FORWARD_POLICY: DROP
  DEFAULT_APPLICATION_POLICY: SKIP
  MANAGE_BUILTINS: "no"
  IPT_SYSCTL: /etc/ufw/sysctl.conf
  IPT_MODULES: ""